### ISSUE TITLE
The speed to switch file is too slow

### ISSUE THREAD

**Issue by qcq** [andriyko/sublime-robot-framework-assistant#40] opened 2016-01-27 08:49 UTC
sublime 3 Beta
I do not know whether just me against this question.
When I switch one robot file with another one(both already opened) I can get this felling obviously.
may be the plugin need time to parse the whole files. May be we can find some way to solve this question.

**Comment by andriyko** [comment] 2016-02-21 14:18
@aaltat do you experience the same issue? I cannot reproduce it.

**Comment by aaltat** [comment] 2016-02-21 14:46
I haven't noticed that switch between tab would be slow. I have +2000 keywords in use and haven't encountered slowness.

**Comment by qcq** [comment] 2016-02-22 12:06
may be conflict with other plugin, I will research it deeply. Thanks for your responding. Thanks.

**Comment by aaltat** [comment] 2016-02-22 15:15
Now I recall that one of the git plugins was causing slowness. I'm not anymore using that plugin and can not exactly recall what was the plugin name.

**Comment by aaltat** [comment] 2016-02-29 21:34
Did you find the issue with slowness? Was it this plugin and we should investigate more or some other plugin/issue and we could close this issue?

**Comment by qcq** [comment] 2016-03-03 14:05
I installed many plugins, I also do not know which one can afford that pain. if you say git plugin may cause that problem, I installed Modific, GitGutter. May be that will useful. Thanks for your attention.

**Comment by aaltat** [comment] 2016-03-30 19:34
@qcq do you still have an issue with this plugin or can we close this issue.

**Closed** 2016-04-01 13:37 UTC
