### ISSUE TITLE
failed go to source of item at caret (either Library, Resource, Keyword or Variable);

### ISSUE THREAD

**Issue by yili1992** [andriyko/sublime-robot-framework-assistant#39] opened 2015-12-08 10:37 UTC
After scan all , my Robot Framework Assistant\robot_data\resourcs , Robot Framework Assistant\robot_data\current and Robot Framework Assistant\robot_data\current are empty.
I can't go to  source of item at caret.

**Comment by andriyko** [comment] 2016-01-25 11:36
Maybe you can give some output from ST console?

**Comment by andriyko** [comment] 2016-02-21 14:16
Could not reproduce. Also did not receive any additional input from reporter. Closing.

**Closed by andriyko** 2016-02-21 14:16 UTC
